// Registro de sesiones a prueba de olvidos (RUTINA-FINAL.md, 2 y 14).
import { test, expect } from '@playwright/test'
import { limpiar, reloj, empezarSesion, menu, registrar, HOY } from './comun.mjs'

test.beforeEach(async ({ page }) => {
  page.on('dialog', (d) => d.accept())
})

test('instalación nueva: "Pon al día tu semana" una sola vez, con el 7 oct como A; luego toca B y si se borra esa A vuelve a tocar A', async ({ page }) => {
  await reloj(page)
  await page.goto('?seed=0')
  await page.waitForTimeout(500)
  await page.evaluate(() => localStorage.clear())
  await page.goto('?seed=0&fresco=1')
  await page.waitForTimeout(600)
  await page.goto('')
  await expect(page.getByText('Pon al día tu semana')).toBeVisible()
  const filas = page.locator('.dia-fila')
  await expect(filas).toHaveCount(3)
  await expect(filas.nth(2)).toContainText('miércoles 7, hoy')
  await expect(filas.nth(2).locator('.dia-boton.marcado')).toHaveText('A')
  await expect(filas.nth(0).locator('.dia-boton.marcado')).toHaveText('No fui')
  await page.getByRole('button', { name: 'Listo' }).click()
  await expect(page.getByText('Hoy toca B · la última fue A el miércoles 7')).toBeVisible()
  await expect(page.getByText('Semana: 1 de 3')).toBeVisible()
  // una sola vez
  await page.goto('')
  await expect(page.getByText('Pon al día tu semana')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /^Empezar/ })).toBeVisible()
  // si se borra la A del 7 oct, vuelve a tocar A
  await page.getByRole('button', { name: 'Historial' }).click()
  await page.locator('.lista .fila').first().click()
  await page.locator('.hoja-fondo.abierta .fila', { hasText: /, A / }).first().click()
  await page.getByRole('button', { name: 'Borrar sesión' }).click()
  await page.getByRole('button', { name: 'Hoy' }).click()
  await expect(page.locator('h1')).toContainText('A:')
  await expect(page.getByText(/Hoy toca A · sin sesiones todavía/)).toBeVisible()
})

test('un martes sin registro hace que el miércoles se pregunte por el martes, una sola vez; "No fui" deja seguir', async ({ page }) => {
  // FRIDA el lunes 5; el martes 6 queda sin contestar (sin la lista de noFui que pone ?seed=)
  await limpiar(page, 'hecha')
  await page.evaluate(() => { const s = JSON.parse(localStorage.getItem('gym-app:settings')); s.noFui = []; localStorage.setItem('gym-app:settings', JSON.stringify(s)) })
  await page.goto('')
  await expect(page.getByText('¿Entrenaste el martes 6?')).toBeVisible()
  await expect(page.getByRole('button', { name: /^Empezar/ })).toHaveCount(0)
  await expect(page.locator('.dia-boton.marcado')).toHaveText('A')
  await page.getByRole('button', { name: 'No fui' }).click()
  await expect(page.getByText('martes 6: no fuiste.')).toBeVisible()
  await expect(page.getByRole('button', { name: /^Empezar/ })).toBeVisible()
  await page.goto('')
  await expect(page.getByText('¿Entrenaste el martes 6?')).toHaveCount(0)
})

test('contestar "A" registra la sesión ese día y entonces toca B; "Deshacer" la quita', async ({ page }) => {
  await limpiar(page, 'hecha')
  await page.evaluate(() => { const s = JSON.parse(localStorage.getItem('gym-app:settings')); s.noFui = []; localStorage.setItem('gym-app:settings', JSON.stringify(s)) })
  await page.goto('')
  await page.getByRole('button', { name: 'A', exact: true }).click()
  await expect(page.getByText('martes 6: A registrada.')).toBeVisible()
  await expect(page.getByText('Hoy toca B · la última fue A el martes 6')).toBeVisible()
  await expect(page.getByText('Semana: 2 de 3')).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer' }).click()
  await expect(page.getByText('¿Entrenaste el martes 6?')).toBeVisible()
})

test('el día de Frida sin respuesta se pregunta con Frida marcada; "No fui" activa la pierna', async ({ page }) => {
  await limpiar(page, 'ninguna', '&registro=2026-09-13:B')
  await reloj(page, '2026-09-15T19:00:00')
  await page.goto('')
  await expect(page.getByText('¿Entrenaste el lunes 14?')).toBeVisible()
  await expect(page.locator('.dia-boton.marcado')).toHaveText('Frida')
  await page.getByRole('button', { name: 'No fui' }).click()
  await expect(page.locator('h1')).toContainText('A:')
  await expect(page.getByText(/con pierna \(goblet a 3 series\)/)).toBeVisible()
})

test('una sesión con una sola serie cuenta como hecha aunque nunca se toque Terminar: al día siguiente se cierra sola y toca la otra', async ({ page }) => {
  await limpiar(page, 'hecha')
  await empezarSesion(page)
  await page.getByRole('button', { name: 'Serie hecha' }).click()
  await menu(page, 'Seguir después')
  await expect(page.getByText('Sesión a medias')).toBeVisible()
  // ya cuenta para la semana aunque siga abierta
  await expect(page.getByText('Semana: 2 de 3')).toBeVisible()
  await reloj(page, '2026-10-08T19:00:00')
  await page.goto('')
  await expect(page.getByText('Sesión a medias')).toHaveCount(0)
  await expect(page.getByText('Hoy toca B · la última fue A el miércoles 7')).toBeVisible()
  await page.getByRole('button', { name: 'Historial' }).click()
  await page.locator('.lista .fila').first().click()
  await expect(page.locator('.hoja-fondo.abierta .fila', { hasText: 'A parcial' })).toBeVisible()
})

test('una sesión a medias sin series se descarta sin dejar rastro', async ({ page }) => {
  await limpiar(page, 'hecha')
  await page.getByRole('button', { name: /^Empezar/ }).click()
  await menu(page, 'Seguir después')
  await page.getByRole('button', { name: 'Descartar' }).click()
  await expect(page.getByRole('button', { name: /^Empezar/ })).toBeVisible()
  await page.getByRole('button', { name: 'Historial' }).click()
  await expect(page.locator('.t-listo.num')).toHaveText('1')
})

test('registrar una sesión hecha sin la app: nunca en el futuro, una A o B por día, con Deshacer', async ({ page }) => {
  await limpiar(page, 'hecha')
  await page.getByRole('button', { name: 'Registrar sesión' }).click()
  const hoja = page.locator('.hoja-fondo.abierta')
  expect(await hoja.getByLabel('Fecha').getAttribute('max')).toBe(HOY)
  await hoja.getByLabel('Qué hice').selectOption('B')
  await hoja.getByRole('button', { name: 'Guardar' }).click()
  await expect(page.getByText('miércoles 7: B registrada.')).toBeVisible()
  await expect(page.getByText(/Hoy toca A · la última fue B el miércoles 7/)).toBeVisible()
  // el mismo día otra vez: ofrece cambiarla en vez de duplicar
  await page.getByRole('button', { name: 'Registrar sesión' }).click()
  await hoja.getByLabel('Qué hice').selectOption('A')
  await hoja.getByRole('button', { name: 'Guardar' }).click()
  await expect(hoja.getByText('El miércoles 7 ya tiene B. ¿La cambio a A?')).toBeVisible()
  await hoja.getByRole('button', { name: 'Cambiar a A' }).click()
  await expect(page.getByText(/Hoy toca B · la última fue A el miércoles 7/)).toBeVisible()
  await expect(page.getByText('Semana: 2 de 3')).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer' }).click()
  await expect(page.getByText(/Hoy toca A · la última fue B el miércoles 7/)).toBeVisible()
})

test('desde Historial también se registra y se puede cambiar qué hice', async ({ page }) => {
  await limpiar(page, 'hecha')
  await registrar(page, '2026-10-06', 'B')
  await expect(page.getByText(/Hoy toca A · la última fue B el martes 6/)).toBeVisible()
  await page.getByRole('button', { name: 'Historial' }).click()
  await page.locator('.lista .fila').first().click()
  await page.locator('.hoja-fondo.abierta .fila', { hasText: 'martes 6, B registrada' }).click()
  await page.locator('.hoja-fondo.abierta').getByLabel('Qué hice').last().selectOption('A')
  await page.locator('.hoja-fondo.abierta').getByRole('button', { name: 'Cerrar' }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('.hoja-fondo.abierta')).toHaveCount(0)
  await page.getByRole('button', { name: 'Hoy' }).click()
  await expect(page.getByText(/Hoy toca B · la última fue A el martes 6/)).toBeVisible()
})
