// Capturas de la sesión guiada: ejercicio, descanso y resumen. Uso: node scripts/capturas-sesion.mjs
import { chromium, devices } from 'playwright'
import { mkdirSync } from 'node:fs'
const dir = process.env.CAPTURAS_DIR ?? 'capturas'
mkdirSync(dir, { recursive: true })
const browser = await chromium.launch()
const ctx = await browser.newContext({ ...devices['iPhone 14'], viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, colorScheme: 'dark' })
const page = await ctx.newPage()
await page.goto('http://localhost:5173/gym-app/?seed=1')
await page.waitForTimeout(1200)
await page.evaluate(() => localStorage.removeItem('gym-app:sesion-activa'))
await page.goto('http://localhost:5173/gym-app/')
await page.waitForTimeout(800)
await page.screenshot({ path: `${dir}/hoy.png` })
await page.getByRole('button', { name: /^Empezar/ }).click()
await page.waitForTimeout(600)
await page.screenshot({ path: `${dir}/sesion-calentamiento.png` })
await page.getByRole('button', { name: 'Arrancar' }).click()
await page.waitForTimeout(400)
await page.getByRole('button', { name: /seguir/i }).click()
await page.waitForTimeout(900)
await page.screenshot({ path: `${dir}/sesion-ejercicio-1.png` })
await page.getByRole('button', { name: 'Serie hecha' }).click()
await page.waitForTimeout(900)
await page.screenshot({ path: `${dir}/sesion-descanso.png` })
await page.getByRole('button', { name: 'Saltar' }).click()
await page.waitForTimeout(900)
await page.screenshot({ path: `${dir}/sesion-ejercicio-2.png` })
await page.getByRole('button', { name: 'Serie hecha' }).click()
await page.waitForTimeout(500)
await page.getByRole('button', { name: 'Saltar' }).click()
await page.waitForTimeout(500)
await page.getByRole('button', { name: 'Serie hecha' }).click()
await page.waitForTimeout(500)
await page.screenshot({ path: `${dir}/sesion-descanso-final.png` })
await page.getByRole('button', { name: 'Saltar' }).click()
await page.waitForTimeout(700)
await page.screenshot({ path: `${dir}/sesion-ejercicio-completo.png` })
await page.locator('button.fm-foto').click()
await page.waitForTimeout(600)
await page.screenshot({ path: `${dir}/sesion-tecnica.png` })
await page.keyboard.press('Escape')
await page.waitForTimeout(400)
await page.getByRole('button', { name: /Salir o cambiar/ }).click()
await page.waitForTimeout(600)
await page.screenshot({ path: `${dir}/sesion-menu.png` })
await page.getByRole('button', { name: 'Terminar sesión' }).click()
await page.waitForTimeout(900)
await page.screenshot({ path: `${dir}/sesion-resumen.png` })
await browser.close()
console.log('listo:', dir)
