// Capturas de la sesión guiada. Uso: node scripts/capturas-sesion.mjs
import { chromium, devices } from 'playwright'
import { mkdirSync } from 'node:fs'
const dir = process.env.CAPTURAS_DIR ?? 'capturas'
mkdirSync(dir, { recursive: true })
const browser = await chromium.launch()
const ctx = await browser.newContext({ ...devices['iPhone 14'], viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, colorScheme: 'dark' })
const page = await ctx.newPage()
const foto = async (n) => { await page.waitForTimeout(900); await page.screenshot({ path: `${dir}/${n}.png` }) }
await page.goto('http://localhost:5173/gym-app/?seed=1')
await page.waitForTimeout(1200)
await page.evaluate(() => localStorage.removeItem('gym-app:sesion-activa'))
await page.goto('http://localhost:5173/gym-app/')
await page.waitForTimeout(800)
await page.getByRole('button', { name: /^Empezar/ }).click()
await foto('sesion-calentamiento')
await page.getByRole('button', { name: 'Empezar calentamiento' }).click()
await foto('sesion-calentamiento-corriendo')
await page.getByRole('button', { name: 'Ya, seguir' }).click()
await foto('sesion-ejercicio-1')
await page.getByRole('button', { name: 'Serie hecha' }).click()
await foto('sesion-descanso')
// recarga a media cuenta: el timer debe seguir exacto
await page.reload()
await page.waitForTimeout(800)
await page.getByRole('button', { name: 'Seguir' }).click()
await foto('sesion-descanso-recargado')
await page.getByRole('button', { name: 'Saltar descanso' }).click()
await foto('sesion-ejercicio-2')
await page.getByRole('button', { name: 'Serie hecha' }).click()
await page.waitForTimeout(400)
await page.getByRole('button', { name: 'Saltar descanso' }).click()
await foto('sesion-ejercicio-3')
await page.getByRole('button', { name: 'Serie hecha' }).click()
await foto('sesion-descanso-final')
await page.getByRole('button', { name: 'Saltar descanso' }).click()
await foto('sesion-ejercicio-siguiente')
await page.getByRole('button', { name: 'Técnica', exact: true }).click()
await foto('sesion-tecnica')
await page.keyboard.press('Escape')
await page.waitForTimeout(400)
await page.getByRole('button', { name: /Salir o cambiar/ }).click()
await foto('sesion-menu')
await page.getByRole('button', { name: /Terminar sesión/ }).click()
await foto('sesion-resumen')
await browser.close()
console.log('listo:', dir)
